// let title = document.getElementById("title");
// let category = document.getElementById("category");
// let price = document.getElementById("price");
// let tax = document.getElementById("tax");
// let ads = document.getElementById("ads");
// let discount = document.getElementById("discount");
// let total = document.getElementById("total");
// let count = document.getElementById("count");
// let search = document.getElementById("search");
// console.log(title, category, price, tax, ads, discount, total, count, search);